# The URL the site will be built for
base_url = "https://ethan.haus"

title = "Ethan Turkeltaub"
description = "Brooklyn-based software engineer working at Stripe"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
socials = [
  {name = "GitHub", link = "https://github.com/ethnt"},
  {name = "LinkedIn", link = "https://www.linkedin.com/in/ethan-turkeltaub-592122a3/"},
  {name = "Twitter", link = "https://twitter.com/ethnt"}
]
